server.port=8081

spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=${JWT_SECRET:bXlTZWNyZXRLZXlGb3JFZHVDb21tZXJjZUFwcGxpY2F0aW9u}
jwt.expiration=86400000
